export type AgentServiceErrorCode =
  | 'AGENT_NAME_REQUIRED'
  | 'AGENT_NAME_INVALID'
  | 'AGENT_NOT_FOUND'
  | 'AGENT_CONFIG_NOT_FOUND'
  | 'AGENT_CONFIG_INVALID'
  | 'AGENT_CONFIG_UNSTABLE'
  | 'AGENT_CONFIG_AVATAR_INVALID'
  | 'AGENT_CONFIG_EDIT_UNSUPPORTED'
  | 'AGENT_CONFIG_REVISION_CONFLICT'
  | 'AGENT_CONFIG_INSTANCE_CONFLICT'
  | 'AGENT_CONFIG_INSTANCE_REQUIRED'
  | 'AGENT_IMPORT_SECRET_FORBIDDEN'
  | 'AGENT_IMPORT_DIGEST_MISMATCH'
  | 'AGENT_IMPORT_ISSUES_UNACCEPTED'
  | 'AGENT_NAME_CONFLICT'
  | 'AGENT_REQUEST_REF_INVALID'
  | 'CANONICAL_AGENT_NOT_AVAILABLE'
  | 'LEGACY_HISTORY_UNAVAILABLE'
  | 'BUILTIN_AGENT_NAME_CONFLICT'
  | 'AMBIGUOUS_AGENT_NAME'
  | 'BUILTIN_AGENT_IMMUTABLE'
  | 'BUILTIN_AGENT_DELETE_FORBIDDEN'
  | 'PRIMARY_AGENT_IMMUTABLE'
  | 'PRIMARY_AGENT_IDENTITY_CONFLICT'
  | 'LEGACY_PRIMARY_WRITE_FORBIDDEN'
  | 'AGENT_ROLE_CONFLICT'
  | 'CONTENT_POLICY_VIOLATION'
  | 'VALIDATION_ERROR';

export class AgentServiceError extends Error {
  readonly status: number;

  constructor(
    readonly code: AgentServiceErrorCode,
    message: string,
    status = statusFor(code),
    readonly details?: Readonly<Record<string, unknown>>,
  ) {
    super(message);
    this.name = 'AgentServiceError';
    this.status = status;
  }
}

function statusFor(code: AgentServiceErrorCode): number {
  return {
    AGENT_NAME_REQUIRED: 400,
    AGENT_NAME_INVALID: 400,
    AGENT_REQUEST_REF_INVALID: 400,
    AGENT_NOT_FOUND: 404,
    AGENT_CONFIG_NOT_FOUND: 409,
    AGENT_CONFIG_INVALID: 422,
    AGENT_CONFIG_UNSTABLE: 409,
    AGENT_CONFIG_AVATAR_INVALID: 422,
    AGENT_CONFIG_EDIT_UNSUPPORTED: 409,
    AGENT_CONFIG_REVISION_CONFLICT: 409,
    AGENT_CONFIG_INSTANCE_CONFLICT: 409,
    AGENT_CONFIG_INSTANCE_REQUIRED: 400,
    AGENT_IMPORT_SECRET_FORBIDDEN: 422,
    AGENT_IMPORT_DIGEST_MISMATCH: 409,
    AGENT_IMPORT_ISSUES_UNACCEPTED: 422,
    CANONICAL_AGENT_NOT_AVAILABLE: 503,
    LEGACY_HISTORY_UNAVAILABLE: 503,
    BUILTIN_AGENT_NAME_CONFLICT: 409,
    AGENT_NAME_CONFLICT: 409,
    AMBIGUOUS_AGENT_NAME: 409,
    BUILTIN_AGENT_IMMUTABLE: 403,
    BUILTIN_AGENT_DELETE_FORBIDDEN: 403,
    PRIMARY_AGENT_IMMUTABLE: 403,
    PRIMARY_AGENT_IDENTITY_CONFLICT: 409,
    LEGACY_PRIMARY_WRITE_FORBIDDEN: 403,
    AGENT_ROLE_CONFLICT: 409,
    CONTENT_POLICY_VIOLATION: 422,
    VALIDATION_ERROR: 400,
  }[code];
}
