export const CONVERSATION_MUTATION_NOT_SUPPORTED = 'CONVERSATION_MUTATION_NOT_SUPPORTED' as const;
export const MESSAGE_BOUNDARY_NOT_FOUND = 'MESSAGE_BOUNDARY_NOT_FOUND' as const;
export const MESSAGE_BOUNDARY_INVALID = 'MESSAGE_BOUNDARY_INVALID' as const;
export const HISTORY_IDENTITY_CONFLICT = 'HISTORY_IDENTITY_CONFLICT' as const;
export const HISTORY_CHAIN_CORRUPT = 'HISTORY_CHAIN_CORRUPT' as const;
export const CONVERSATION_MUTATION_BUSY = 'CONVERSATION_MUTATION_BUSY' as const;
export const CONVERSATION_MUTATION_REQUEST_CONFLICT =
  'CONVERSATION_MUTATION_REQUEST_CONFLICT' as const;
export const TURN_ABORT_TIMEOUT = 'TURN_ABORT_TIMEOUT' as const;
export const FORK_COPY_FAILED = 'FORK_COPY_FAILED' as const;
export const FORK_WORKTREE_UNAVAILABLE = 'FORK_WORKTREE_UNAVAILABLE' as const;
export const FORK_WORKTREE_SOURCE_CHANGED = 'FORK_WORKTREE_SOURCE_CHANGED' as const;
export const REWIND_DISPLAY_COMMIT_FAILED = 'REWIND_DISPLAY_COMMIT_FAILED' as const;
export const EDIT_SUBMIT_FAILED_AFTER_REWIND = 'EDIT_SUBMIT_FAILED_AFTER_REWIND' as const;
export const EDIT_RESTART_NEEDS_RESUBMIT = 'EDIT_RESTART_NEEDS_RESUBMIT' as const;
export const EDIT_RESTART_NEEDS_NEW_OPERATION = 'EDIT_RESTART_NEEDS_NEW_OPERATION' as const;
export const FORK_RECOVERY_FAILED = 'FORK_RECOVERY_FAILED' as const;

export type ConversationMutationErrorCode =
  | typeof CONVERSATION_MUTATION_NOT_SUPPORTED
  | typeof MESSAGE_BOUNDARY_NOT_FOUND
  | typeof MESSAGE_BOUNDARY_INVALID
  | typeof HISTORY_IDENTITY_CONFLICT
  | typeof HISTORY_CHAIN_CORRUPT
  | typeof CONVERSATION_MUTATION_BUSY
  | typeof CONVERSATION_MUTATION_REQUEST_CONFLICT
  | typeof TURN_ABORT_TIMEOUT
  | typeof FORK_COPY_FAILED
  | typeof FORK_WORKTREE_UNAVAILABLE
  | typeof FORK_WORKTREE_SOURCE_CHANGED
  | typeof REWIND_DISPLAY_COMMIT_FAILED
  | typeof EDIT_SUBMIT_FAILED_AFTER_REWIND
  | typeof EDIT_RESTART_NEEDS_RESUBMIT
  | typeof EDIT_RESTART_NEEDS_NEW_OPERATION
  | typeof FORK_RECOVERY_FAILED;
